apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dwk-exercises
  name: pingpong-config
data:
  PGHOST: "postgres.dwk-exercises.svc.cluster.local"
  PGPORT: "5432"
  PGUSER: "pingpong"
  PGDATABASE: "pingpong"
  PORT: "80"
