apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-exercises
  name: pingpong
spec:
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: eu.gcr.io/strax-dwk/pingpong
          envFrom:
            - configMapRef:
                name: pingpong-config
            - secretRef:
                name: pingpong-secret
          readinessProbe:
            httpGet:
              port: 80
              path: /healthz
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
