apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-exercises
  name: main-app-dep
spec:
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - name: main-app
          image: eu.gcr.io/strax-dwk/main-app@sha256:747090156528d3d43bb24bd7fd17ca9faba31a4facf6977ce0ce62aab714b68c
