apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-exercises
  name: main-app-dep
spec:
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - name: main-app
          image: eu.gcr.io/strax-dwk/main-app@sha256:406b6acfc772c7d2a955ce23080e44ea7b6f6b66e782277f8f61a4f6c3af8343
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  key: message
                  name: main-app