apiVersion: v1
kind: Service
metadata:
  namespace: dwk-exercises
  name: main-app
  annotations:
    cloud.google.com/backend-config: |
      {"ports": {"80": "http-backendconfig"}}
spec:
  type: NodePort
  selector:
    app: main-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
