apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dwk-exercises
  name: ingress
spec:
  rules:
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /pingpong
        backend:
          service:
            name: pingpong-svc
            port: 
              number: 80
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: main-app-svc
            port:
              number: 80
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: dwk-exercises
  name: http-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 15
    type: HTTP
    requestPath: /health
    port: 80