protoc:
    mkdir -p pkg/protos/pingpong
    protoc -I ../protos --go_out=paths=source_relative:pkg/protos/pingpong --go-grpc_out=pkg/protos/pingpong --go-grpc_opt=paths=source_relative ../protos/pingpong.proto
