apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/ingress.yaml
- manifests/postgres.yaml
- main-app/manifests/configmap.yaml
- main-app/manifests/deployment.yaml
- main-app/manifests/service.yaml
- pingpong/manifests/config.yaml
- pingpong/manifests/deployment.yaml
- pingpong/manifests/service.yaml
images:
- name: eu.gcr.io/strax-dwk/pingpong
- name: eu.gcr.io/strax-dwk/main-app
