apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: frontend
  namespace: dwk-project
spec:
  interval: 1m
  image: ghcr.io/strax/dwk-project-frontend
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: frontend
  namespace: dwk-project
spec:
  imageRepositoryRef:
    name: frontend
  filterTags:
    pattern: 'main-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: api
  namespace: dwk-project
spec:
  interval: 1m
  image: ghcr.io/strax/dwk-project-api
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: api
  namespace: dwk-project
spec:
  imageRepositoryRef:
    name: api
  filterTags:
    pattern: 'main-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: broadcaster
  namespace: dwk-project
spec:
  interval: 1m
  image: ghcr.io/strax/dwk-project-broadcaster
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: broadcaster
  namespace: dwk-project
spec:
  imageRepositoryRef:
    name: broadcaster
  filterTags:
    pattern: 'main-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: git
  namespace: dwk-project
spec:
  interval: 1m
  url: https://github.com/strax/dwk-2021
  ref:
    branch: main
---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: automation
  namespace: dwk-project
spec:
  sourceRef:
    kind: GitRepository
    name: git
  interval: 1m
  update:
    strategy: Setters
    path: ./project
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        An automated update from FluxBot
        [ci skip]
    push:
      branch: main
