apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: dwk-project
  name: ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: api
            port:
              number: 80
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port:
              number: 80
