---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
  namespace: dwk-project
spec:
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
  interval: 1m0s
  releaseName: nats
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dwk-project-nats
  namespace: prometheus
  labels:
    release: kube-prometheus-stack-1623060733
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
  endpoints:
    - interval: 10s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - dwk-project
