apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dwk-exercises
  name: main-app
spec:
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - name: main-app
          image: eu.gcr.io/strax-dwk/main-app@sha256:356f8360daf0bc90371044509647f360ff41ea57a4c0a8aea91c83b3c4aae367
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  key: message
                  name: main-app
          readinessProbe:
            httpGet:
              port: 80
              path: /healthz
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
