// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pingpong

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PingpongServiceClient is the client API for PingpongService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingpongServiceClient interface {
	GetStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Stats, error)
}

type pingpongServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPingpongServiceClient(cc grpc.ClientConnInterface) PingpongServiceClient {
	return &pingpongServiceClient{cc}
}

func (c *pingpongServiceClient) GetStats(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := c.cc.Invoke(ctx, "/pingpong.PingpongService/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingpongServiceServer is the server API for PingpongService service.
// All implementations must embed UnimplementedPingpongServiceServer
// for forward compatibility
type PingpongServiceServer interface {
	GetStats(context.Context, *emptypb.Empty) (*Stats, error)
	mustEmbedUnimplementedPingpongServiceServer()
}

// UnimplementedPingpongServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPingpongServiceServer struct {
}

func (UnimplementedPingpongServiceServer) GetStats(context.Context, *emptypb.Empty) (*Stats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedPingpongServiceServer) mustEmbedUnimplementedPingpongServiceServer() {}

// UnsafePingpongServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingpongServiceServer will
// result in compilation errors.
type UnsafePingpongServiceServer interface {
	mustEmbedUnimplementedPingpongServiceServer()
}

func RegisterPingpongServiceServer(s grpc.ServiceRegistrar, srv PingpongServiceServer) {
	s.RegisterService(&PingpongService_ServiceDesc, srv)
}

func _PingpongService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingpongServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpong.PingpongService/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingpongServiceServer).GetStats(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PingpongService_ServiceDesc is the grpc.ServiceDesc for PingpongService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingpongService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pingpong.PingpongService",
	HandlerType: (*PingpongServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _PingpongService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pingpong.proto",
}
