apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: dwk-exercises
  name: dailytodo-cronjob
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dailytodo
              image: eu.gcr.io/strax-dwk/dailytodo@sha256:9fd9c6a463d53802b685ed40f3a9b2c4df2fc08019fd4d0edd47f7c9be841f4b
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
