apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: dwk-project
  name: image-updater
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: volume1
              persistentVolumeClaim:
                claimName: project-pvc
          containers:
            - name: project-image-updater
              image: eu.gcr.io/google-containers/toolbox
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - curl https://picsum.photos/400/400.webp -L -o /mnt/volume1/picsum-400-400.webp
              volumeMounts:
                - mountPath: /mnt/volume1
                  name: volume1
          restartPolicy: OnFailure
