apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dwk-project
  name: project-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
