apiVersion: v1
kind: Service
metadata:
  namespace: dwk-project
  name: api
  annotations:
    cloud.google.com/backend-config: |
      {"ports": { "80": "http-backendconfig" } }
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
