name: Teardown project environment
on:
  [delete]
concurrency:
  group: ${{ github.event.ref }}
  cancel-in-progress: true
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
jobs:
  teardown:
    if: ${{ github.event.ref != 'main' }}
    name: "Teardown environment"
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Delete namespace
        run: |
          NAMESPACE="dwk-project-${{ github.event.ref }}"
          kubectl delete namespace "$NAMESPACE"