apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
  - image: ghcr.io/strax/dwk-project-api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifests/config.yaml
    - manifests/deployment.yaml
    - manifests/service.yaml
